### ISSUE TITLE
a couple of bugs (paperui)

### ISSUE THREAD

**Issue by azim0ff** [openhab/smarthome#13] opened 2015-05-21 03:20 UTC
Hello friends, I'm working on a binding for my own gadget and I had observed the following with respect to the paper-ui. These were found in the latest build from source (as of May 19 2015)

1. There are some glitches with the initial layout (control boxes covering each other up). However, if one does an in-page refresh (orang-white refresh button in upper RH corner) the layout fixes itself.

2. At times the paper-ui screen gets stuck and doesn't update Thing status. Forcing a browser-cache flush + reloading fixes things.

Browser: Firefox 38 32bit Linux (Ubuntu 12.04)

Edit: can't seem to attach a "paperui" label...

**Comment by dnobel** [comment] 2015-05-23 09:22
I can confirm the first one. It is fixed with with PR #14. But I can not reproduce the second issue.

Can you please give some more information on that? What exactly means the screen stucks?

**Comment by azim0ff** [comment] 2015-05-24 14:15
I guess what I mean is - the updates from openhab aren't reflected in the UI. I'm not fully certain of the steps to get it into that state, other than that it happens as I rebuild the project and stop/start openhab. I will try to narrow down the exact cause. Feel free to disregard that portion until I can report back with something more tangible.

**Comment by dnobel** [comment] 2015-05-25 09:23
If you restart the openHAB runtime the SSE connection will be interrupted. I did not implement an automatic reconnect so far. But I would consider this a feature, rather than a bug. If you have a running installation, the SSE connection should continuously work without a need for a page reload.

**Comment by sja** [comment] 2015-07-06 12:12
With PR 19 I added reconnect behaviour for Firefox. But please not that it will reconnect but won't re-fetch all values since the connection was lost. Just changes after the reconnection was established are transfered.

**Comment by dnobel** [comment] 2015-07-06 20:19
Is it only working for FF or also for other browsers? In my testing it at least worked with chrome. But from the implementation it only provides one reconnect try after 5 seconds or does it continuously retry?

**Comment by sja** [comment] 2015-07-08 10:43
Answered here: https://github.com/openhab/smarthome.paperui/pull/18#issuecomment-119087123

**Comment by kaikreuzer** [comment] 2015-07-09 07:06
Closing this issue, assuming both things are fixed. If there are still open bugs, please open a new issue at https://github.com/openhab/smarthome.paperui/issues

**Closed by kaikreuzer** 2015-07-09 07:06 UTC
Labels: paperui
